---
project_dir: ~/.script
downloads_dir: ~/Downloads

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes
configure_npm: yes
configure_extra: yes
configure_dock: yes

dotfiles_repo: https://github.com/flemzord/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc
  - .zshrc.local

homebrew_installed_packages:
  - autoconf
  - automake
  - bash-completion
  - chromedriver
  - git
  - go
  - gpg
  - node
  - yarn
  - nvm
  - ssh-copy-id
  - wget
  - curl
  - htop
  - kubernetes-cli
  - kubernetes-helm
  - mas
  - ncdu
  - packer
  - scw
  - terraform
  - terminal-notifier
  - zsh
  - tree
  - dockutil
  - watch
  - zplug


homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - sequel-pro
  - google-cloud-sdk
  - google-backup-and-sync
  - atom
  - alfred
  - iterm2
  - spotify
  - vagrant
  - virtualbox
  - dash
  - cleanmymac
  - etcher
  - yakyak
  - tunnelblick
  - gitkraken
  - intellij-idea
  - docker
  - vlc
  - istat-menus
  - franz

npm_global_package:
  - pm2

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 747648890, name: "Telegram" }
  - { id: 409183694, name: "Keynote" }
  - { id: 918858936, name: "Airmail 3" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 557168941, name: "Tweetbot for Twitter" }
  - { id: 715768417, name: "Microsoft Remote Desktop" }
  - { id: 803453959, name: "Slack" }

mas_upgrade_all_apps: yes

osx_script: "~/.osx --no-restart"

dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Rappels
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendrier
  - Terminal
  - Plans
  - Pages
  - Numbers
  - Keynote
  - Préférences Système

dockitems_enabled:
  - name: Airmail 3
    path: "/Applications/Airmail 3.app"
    pos: 1
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 2
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: Pages
    path: "/Applications/Pages.app"
    pos: 4
  - name: Numbers
    path: "/Applications/Numbers.app"
    pos: 5
  - name: Keynote
    path: "/Applications/Keynote.app"
    pos: 6
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 7
  - name: Telegram
    path: "/Applications/Telegram.app"
    pos: 8
  - name: YakYak
    path: "/Applications/YakYak.app"
    pos: 9
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 10
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 11
  - name: Atom
    path: "/Applications/Atom.app"
    pos: 12
  - name: GitKraken
    path: "/Applications/GitKraken.app"
    pos: 13
  - name: Dash
    path: "/Applications/Dash.app"
    pos: 14
  - name: Franz
    path: "/Applications/Franz.app"
    pos: 15
  - name: Préférences Système
    path: "/Applications/System Preferences.app"
    pos: 16
