---
project_dir: ~/.script
downloads_dir: ~/Downloads
dircolors_dir: ~/.dircolors

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes
configure_npm: yes
configure_extra: yes
configure_dock: yes

dotfiles_repo: https://github.com/Jno21/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .macos
  - .zshrc.local

homebrew_installed_packages:
  - autoconf
  - automake
  - bash-completion
  - git
  - go
  - gpg
  - yarn
  - nvm
  - ssh-copy-id
  - wget
  - curl
  - htop
  - kubernetes-cli
  - kubernetes-helm
  - mas
  - ncdu
  - packer
  - zsh
  - tree
  - dockutil
  - watch
  - zplug
  - bat
  - findutils
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnutls
  - grep
  - coreutils
  - binutils
  - diffutils
  - prettyping
  - fzf
  - diff-so-fancy
  - fd
  - tldr
  - ack
  - hadolint
  - tfenv
  - dive
  - nmap

homebrew_taps:
  - homebrew/core
  - homebrew/cask-fonts
  - wagoodman/dive

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - firefox
  - sequel-pro
  - google-cloud-sdk
  - google-backup-and-sync
  - visual-studio-code
  - alfred
  - iterm2
  - spotify
  - dash
  - cleanmymac
  - tunnelblick
  - docker
  - vlc
  - franz
  - dashlane
  - postman
  - emacs
  - font-menlo-for-powerline

npm_global_package:
  - spaceship-prompt

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 803453959, name: "Slack" }
  - { id: 1176895641, name: "Spark" }

mas_upgrade_all_apps: yes

osx_script: "~/.macos --no-restart"

dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Rappels
  - Maps
  - Photos
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendrier
  - Terminal
  - Plans
  - Pages
  - Numbers
  - Keynote

dockitems_enabled:
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 1
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 2
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: Pages
    path: "/Applications/Pages.app"
    pos: 4
  - name: Numbers
    path: "/Applications/Numbers.app"
    pos: 5
  - name: Keynote
    path: "/Applications/Keynote.app"
    pos: 6
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 10
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 11
  - name: Atom
    path: "/Applications/Atom.app"
    pos: 12
  - name: Dash
    path: "/Applications/Dash.app"
    pos: 14
  - name: Franz
    path: "/Applications/Franz.app"
    pos: 15
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 16
